"""
Article loader for converting crawled JSON files to NewsArticle objects.

Handles loading JSON files from the articles/ directory and converting
them to the NewsArticle format expected by the processing pipeline.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from src.models import NewsArticle
from src.indexer.date_parser import DateParser, get_date_parser

logger = logging.getLogger(__name__)


class ArticleLoader:
    """
    Loader for crawled article JSON files.

    Converts JSON files produced by WSJCrawler into NewsArticle objects
    suitable for the embedding and indexing pipeline.

    Example:
        >>> loader = ArticleLoader()
        >>> article = loader.load_file("articles/tech/2026-01-25/intel.json")
        >>> print(article.title)
        Intel Shares Slide...
    """

    # Minimum content length to consider valid
    MIN_CONTENT_LENGTH = 100

    def __init__(self, date_parser: Optional[DateParser] = None) -> None:
        """
        Initialize the loader.

        Args:
            date_parser: Optional DateParser instance (uses singleton if not provided)
        """
        self._date_parser = date_parser or get_date_parser()

    def load_file(self, file_path: str | Path) -> NewsArticle:
        """
        Load a single JSON file and convert to NewsArticle.

        Args:
            file_path: Path to the article JSON file

        Returns:
            NewsArticle: Parsed article object

        Raises:
            FileNotFoundError: If file doesn't exist
            ValueError: If JSON is invalid or content is too short
        """
        file_path = Path(file_path)

        if not file_path.exists():
            raise FileNotFoundError(f"Article file not found: {file_path}")

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON in {file_path}: {e}") from e

        return self._convert_to_article(data, file_path)

    def _convert_to_article(self, data: dict, source_file: Path) -> NewsArticle:
        """
        Convert JSON data to NewsArticle.

        Args:
            data: Parsed JSON data
            source_file: Source file path (for error messages)

        Returns:
            NewsArticle: Converted article

        Raises:
            ValueError: If required fields are missing or invalid
        """
        # Validate required fields
        title = data.get("title", "").strip()
        if not title:
            raise ValueError(f"Missing title in {source_file}")

        content = data.get("content", "").strip()
        if not content:
            raise ValueError(f"Missing content in {source_file}")

        if len(content) < self.MIN_CONTENT_LENGTH:
            raise ValueError(
                f"Content too short ({len(content)} chars) in {source_file}"
            )

        url = data.get("url", "").strip()
        if not url:
            raise ValueError(f"Missing URL in {source_file}")

        # Parse published_at
        published_at_str = data.get("published_at")
        published_at = self._date_parser.parse(published_at_str)

        # Clean up author field (may have newlines)
        author = data.get("author")
        if author:
            author = " ".join(author.split())

        return NewsArticle(
            title=title,
            content=content,
            url=url,
            source=data.get("source", "WSJ"),
            category=data.get("category"),
            author=author,
            published_at=published_at,
            summary=None,  # Will be generated by LLM
            subtitle=data.get("subtitle"),
            is_exclusive=data.get("is_exclusive", False),
        )

    def load_directory(
        self,
        directory: str | Path,
        recursive: bool = True,
    ) -> list[tuple[Path, NewsArticle]]:
        """
        Load all article JSON files from a directory.

        Args:
            directory: Directory containing JSON files
            recursive: Whether to search subdirectories

        Returns:
            list: Tuples of (file_path, NewsArticle) for successfully loaded files

        Note:
            Failed files are logged but don't stop processing.
        """
        directory = Path(directory)

        if recursive:
            json_files = list(directory.rglob("*.json"))
        else:
            json_files = list(directory.glob("*.json"))

        results = []
        for file_path in sorted(json_files):
            try:
                article = self.load_file(file_path)
                results.append((file_path, article))
            except (FileNotFoundError, ValueError) as e:
                logger.warning(f"Failed to load {file_path}: {e}")

        logger.info(f"Loaded {len(results)}/{len(json_files)} articles from {directory}")
        return results

    def validate_file(self, file_path: str | Path) -> tuple[bool, Optional[str]]:
        """
        Validate an article file without fully loading it.

        Args:
            file_path: Path to the article JSON file

        Returns:
            tuple: (is_valid, error_message)
        """
        try:
            self.load_file(file_path)
            return True, None
        except (FileNotFoundError, ValueError) as e:
            return False, str(e)


# Module-level singleton
_loader: Optional[ArticleLoader] = None


def get_article_loader() -> ArticleLoader:
    """Get singleton ArticleLoader instance."""
    global _loader
    if _loader is None:
        _loader = ArticleLoader()
    return _loader
